name: black
run-name: Formatting code pushed by ${{ github.actor }}
on: [push, workflow_dispatch]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11.1
    - run: python -m pip install black
    - run: black --line-length 100
