name: format-and-lint
run-name: Formatting and linting commit ${{ github.sha }}
on: [push, workflow_dispatch]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Setup CPython
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11.1
        
    - name: Install black
      run: python -m pip install black
      
    - name: Format with black
      run: black src/ --line-length 100 # Formats only changed files
    
  pylint:
    runs-on: ubuntu-latest
    env:
      PYLINT_OUTPUT: 'If you''re seeing this, the action probably didn''t run correctly.'
    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Setup CPython
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11.1
      
    - name: Install pylint
      run: python -m pip install pylint
    
    - name: Lint with pylint
      run: echo $(pylint src/) >> $env:PYLINT_OUTPUT
    
    - uses: peter-evans/commit-comment@v2.0.1
      with:
        body: |
          $PYLINT_OUTPUT
          - Will remove this later; this is a test comment for this Action
