name: lint
run-name: Linting commit ${{ github.sha }}
on: [push, workflow_dispatch]
jobs:
  black:
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-latest
    env:
      BLACK_OUTPUT: 'If you''re seeing this, the action probably didn''t run correctly.'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.3.0
    
    - name: Setup CPython
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11.1
        
    - name: Install black
      run: python -m pip install black
      
    - name: Format with black
      run: echo BLACK_OUTPUT=$(black src/ --check --line-length 100) >> $BLACK_OUTPUT
    
    - name: Comment with output
      if: always()
      uses: peter-evans/commit-comment@v2.0.1
      with:
        body: |
          # Black Output
          $BLACK_OUTPUT
          
  pylint:
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-latest
    env:
      PYLINT_OUTPUT: 'If you''re seeing this, the action probably didn''t run correctly.'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.3.0
    
    - name: Setup CPython
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11.1
    
    - name: Install pylint
      run: python -m pip install pylint
    
    - name: Lint with pylint
      run: echo PYLINT_OUTPUT=$(pylint src/) >> $PYLINT_OUTPUT
    
    - name: Comment with output
      if: always()
      uses: peter-evans/commit-comment@v2.0.1
      with:
        body: |
          # Pylint Output
          $PYLINT_OUTPUT
